// Mocks generated by Mockito 5.4.6 from annotations
// in haven/test/pages/identity_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:haven/src/services/identity_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIdentity_0 extends _i1.SmartFake implements _i2.Identity {
  _FakeIdentity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IdentityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityService extends _i1.Mock implements _i2.IdentityService {
  MockIdentityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#hasIdentity, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i2.Identity?> getIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentity, []),
            returnValue: _i3.Future<_i2.Identity?>.value(),
          )
          as _i3.Future<_i2.Identity?>);

  @override
  _i3.Future<_i2.Identity> createIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#createIdentity, []),
            returnValue: _i3.Future<_i2.Identity>.value(
              _FakeIdentity_0(this, Invocation.method(#createIdentity, [])),
            ),
          )
          as _i3.Future<_i2.Identity>);

  @override
  _i3.Future<_i2.Identity> importFromNsec(String? nsec) =>
      (super.noSuchMethod(
            Invocation.method(#importFromNsec, [nsec]),
            returnValue: _i3.Future<_i2.Identity>.value(
              _FakeIdentity_0(this, Invocation.method(#importFromNsec, [nsec])),
            ),
          )
          as _i3.Future<_i2.Identity>);

  @override
  _i3.Future<String> exportNsec() =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#exportNsec, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> sign(_i5.Uint8List? messageHash) =>
      (super.noSuchMethod(
            Invocation.method(#sign, [messageHash]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#sign, [messageHash]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getPubkeyHex() =>
      (super.noSuchMethod(
            Invocation.method(#getPubkeyHex, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getPubkeyHex, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#deleteIdentity, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
