#!/usr/bin/env bash
# CI guard: the flutter_rust_bridge-generated files are exactly the bytes that
# were pinned, and they were stamped by the codegen version this repo pins.
#
# # Why this exists
#
# The bridge's generated files are the only place where the Rust side's meaning
# of a value and the Dart side's meaning of it are written down twice, and
# nothing in the repository compares the two halves:
#
#   * `cargo check` type-checks each half separately. `SseEncode` writing `1`
#     for a variant `SseDecode` reads as `0` is well-typed on both sides.
#   * `cargo test` and `flutter test` never meet: `rust_builder` has no test
#     that crosses the bridge, and the Dart tests drive fakes.
#   * `FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH` inside `frb_generated.rs` is
#     derived from the INPUT (`api.rs`), not from the generated file's own
#     content, so editing the generated file leaves it unchanged. It detects a
#     stale regeneration; it cannot detect a hand-edit.
#   * no workflow regenerates and diffs — the only mentions of `frb_generated`
#     in `.github/workflows/` are coverage exclusions.
#
# So a one-character edit to a generated codec lands green. `BacklogOutcomeFfi`
# is the first enum the burst path sends Rust→Dart whose two values have
# OPPOSITE safety meanings — `Settled` = "every endpoint replayed, safe to
# encrypt now", `TimedOut` = "promises nothing" — and inverting its encoding
# makes every burst read a real timeout as settled and publish at a stale
# epoch, which peers can only decrypt from a past-epoch key.
#
# # Why hashes rather than a regeneration
#
# Regenerating and diffing is the stronger check and it is cheap to RUN (~2 s
# locally), but not cheap to REACH: `flutter_rust_bridge_codegen` is a Rust
# binary that has to be built or fetched, and `repo-guards.yml` is deliberately
# a toolchain-free pure-grep job. Pinning the content hashes catches the failure
# that actually happens — generated bytes changed by something other than the
# codegen — with no toolchain and no runtime, and it is fail-closed on a
# generated file being added or deleted as well as edited.
#
# What it does NOT prove is that the pinned bytes ARE the codegen's output. The
# pin file is therefore written only by `scripts/regenerate_frb.sh`, which runs
# the codegen first; a hand-edit re-pinned by hand still has to show up in
# review as a generated file changing with no input change, which is a state
# regeneration cannot produce.
#
# The codegen-version check is the other half: a repin from a DIFFERENT codegen
# would otherwise be indistinguishable from a hand-edit, so every generated
# file's `@generated by` stamp must match the `flutter_rust_bridge` version
# pinned in both `haven/rust_builder/Cargo.toml` and `haven/pubspec.yaml`.
#
# Usage:
#   check_generated_bridge_pinned.sh              # check the tree
#   check_generated_bridge_pinned.sh --repin      # rewrite the pin file
#   check_generated_bridge_pinned.sh --self-test  # hermetic fixtures
#
# Exit codes:
#   0  the generated files match their pins
#   1  a pin mismatch, an unpinned/missing generated file, or a version drift
#   2  expected paths missing (misconfiguration)

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PIN_FILE="${REPO_ROOT}/scripts/ci/generated_bridge.sha256"
# The two roots flutter_rust_bridge writes into, per haven/flutter_rust_bridge.yaml
# (`dart_output: lib/src/rust`, `rust_root: rust_builder`).
GENERATED_ROOTS=('haven/lib/src/rust' 'haven/rust_builder/src')
GENERATED_MARK='@generated by `flutter_rust_bridge`'

log() {
  printf '\033[1;34m[check_generated_bridge_pinned]\033[0m %s\n' "$*"
}

_lf=0
lfail() {
  printf '\033[1;31m[check_generated_bridge_pinned] FAIL:\033[0m %s\n' "$*" >&2
  _lf=1
}

sha256_of() { # <file>
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# Every generated file under <root>..., as repo-relative paths, sorted.
#
# Discovery is by the codegen's own header MARKER, not by a filename list: a
# generated file this guard has never heard of still gets found (and, being
# unpinned, still fails), which is what keeps the pin honest as the bridge's
# output grows new modules.
discover_generated() { # <repo-root> <root>...
  local root="$1" dir f
  shift
  for dir in "$@"; do
    [[ -d "${root}/${dir}" ]] || continue
    while IFS= read -r f; do
      head -n 3 "${f}" | grep -qF "${GENERATED_MARK}" && printf '%s\n' "${f#"${root}/"}"
    done < <(find "${root}/${dir}" -type f \( -name '*.rs' -o -name '*.dart' \))
  done | LC_ALL=C sort
}

# The codegen version stamped in a generated file's header, e.g. `2.11.1`.
stamped_version() { # <file>
  head -n 3 "$1" | sed -n 's/.*@generated by `flutter_rust_bridge`@ \([0-9][0-9.]*\)\.$/\1/p' | head -n 1
}

# ---------------------------------------------------------------------------
# 1 + 2. The pinned SET and the pinned BYTES.
# ---------------------------------------------------------------------------
check_pins() { # <repo-root> <pin-file>
  local root="$1" pins="$2"
  _lf=0

  if [[ ! -f "${pins}" ]]; then
    lfail "no pin file at ${pins#"${root}/"}. Regenerate the bridge with scripts/regenerate_frb.sh, which writes it."
    return 1
  fi

  local found
  found="$(discover_generated "${root}" "${GENERATED_ROOTS[@]}")"
  if [[ -z "${found}" ]]; then
    lfail "found no flutter_rust_bridge-generated file under ${GENERATED_ROOTS[*]}. Either the bridge output moved or this scanner stopped matching the '${GENERATED_MARK}' header — both leave the codecs unpinned, so this is a failure, not an empty pass."
    return 1
  fi

  local pinned
  pinned="$(awk '/^[0-9a-f]{64}[[:space:]]/ { print $2 }' "${pins}" | LC_ALL=C sort)"

  local extra missing
  extra="$(LC_ALL=C comm -23 <(printf '%s\n' "${found}") <(printf '%s\n' "${pinned}"))"
  missing="$(LC_ALL=C comm -13 <(printf '%s\n' "${found}") <(printf '%s\n' "${pinned}"))"

  local f
  while IFS= read -r f; do
    [[ -n "${f}" ]] || continue
    lfail "${f} is generated by flutter_rust_bridge but carries no pin. A new generated file is a new pair of codecs nothing compares; run scripts/regenerate_frb.sh so it is pinned with the rest."
  done <<<"${extra}"

  while IFS= read -r f; do
    [[ -n "${f}" ]] || continue
    lfail "${f} is pinned but is no longer a generated file (deleted, or its '${GENERATED_MARK}' header is gone). A pin nobody checks is worse than no pin; run scripts/regenerate_frb.sh."
  done <<<"${missing}"

  # 2. The bytes.
  local want got path
  while read -r want path; do
    [[ "${want}" =~ ^[0-9a-f]{64}$ ]] || continue
    [[ -f "${root}/${path}" ]] || continue
    got="$(sha256_of "${root}/${path}")"
    if [[ "${got}" != "${want}" ]]; then
      lfail "${path} does not match its pin (pinned ${want:0:12}…, found ${got:0:12}…). Nothing compares the Rust and Dart halves of a codec, so an edit here — an inverted SseEncode discriminant, a swapped field order — is well-typed on both sides and silent at runtime. If this change came from the codegen, run scripts/regenerate_frb.sh, which regenerates AND re-pins; if it did not, it must not be in a generated file."
    fi
  done <"${pins}"

  return "$_lf"
}

# ---------------------------------------------------------------------------
# 3. The stamped codegen version == the version both manifests pin.
#
#    Without this a repin from a different codegen is indistinguishable from a
#    hand-edit: both are "the bytes changed and the pin changed with them".
# ---------------------------------------------------------------------------
check_codegen_version() { # <repo-root>
  local root="$1"
  _lf=0

  local cargo="${root}/haven/rust_builder/Cargo.toml"
  local pubspec="${root}/haven/pubspec.yaml"
  local cargo_ver pubspec_ver
  cargo_ver="$(sed -n 's/^flutter_rust_bridge[[:space:]]*=[[:space:]]*"=\{0,1\}\([0-9][0-9.]*\)".*/\1/p' "${cargo}" | head -n 1)"
  pubspec_ver="$(sed -n 's/^[[:space:]]*flutter_rust_bridge:[[:space:]]*\^\{0,1\}\([0-9][0-9.]*\).*/\1/p' "${pubspec}" | head -n 1)"

  if [[ -z "${cargo_ver}" || -z "${pubspec_ver}" ]]; then
    lfail "could not read the flutter_rust_bridge version from haven/rust_builder/Cargo.toml (${cargo_ver:-unset}) and/or haven/pubspec.yaml (${pubspec_ver:-unset}). This guard compares the codegen that STAMPED the generated files against the runtime both halves link; it cannot do that blind."
    return 1
  fi

  if [[ "${cargo_ver}" != "${pubspec_ver}" ]]; then
    lfail "the flutter_rust_bridge runtime versions disagree: Cargo.toml pins ${cargo_ver}, pubspec.yaml pins ${pubspec_ver}. The generated codecs are shared between them, so a version split is a wire-format split."
  fi

  local f stamped
  while IFS= read -r f; do
    [[ -n "${f}" ]] || continue
    stamped="$(stamped_version "${root}/${f}")"
    if [[ -z "${stamped}" ]]; then
      lfail "${f} carries the generated marker but no readable '@generated by \`flutter_rust_bridge\`@ <version>.' stamp. Without it a regeneration by a different codegen cannot be told apart from a hand-edit."
    elif [[ "${stamped}" != "${cargo_ver}" ]]; then
      lfail "${f} was generated by flutter_rust_bridge ${stamped}, but this repo pins ${cargo_ver}. Codec layout is a property of the codegen, so files stamped by two versions are two wire formats sharing one runtime."
    fi
  done < <(discover_generated "${root}" "${GENERATED_ROOTS[@]}")

  return "$_lf"
}

# ---------------------------------------------------------------------------
# THE REGISTRY. One list, driven by the production run AND by `--self-test`, so
# a check that is not wired here cannot be certified by a fixture.
# ---------------------------------------------------------------------------
run_all_checks() { # <repo-root> <pin-file>
  local root="$1" pins="$2" rc=0
  check_pins "${root}" "${pins}" || rc=1
  check_codegen_version "${root}" || rc=1
  return "${rc}"
}

repin() { # <repo-root> <pin-file>
  local root="$1" pins="$2" f
  {
    echo "# sha256 of every flutter_rust_bridge-generated file, written by"
    echo "# scripts/regenerate_frb.sh (which regenerates first) and checked by"
    echo "# scripts/ci/check_generated_bridge_pinned.sh. Never hand-edit: a pin"
    echo "# updated without a regeneration is the exact state this file exists to"
    echo "# make visible."
    while IFS= read -r f; do
      [[ -n "${f}" ]] || continue
      printf '%s  %s\n' "$(sha256_of "${root}/${f}")" "${f}"
    done < <(discover_generated "${root}" "${GENERATED_ROOTS[@]}")
  } >"${pins}"
  log "re-pinned $(awk '/^[0-9a-f]{64}[[:space:]]/' "${pins}" | grep -c .) generated file(s) in ${pins#"${root}/"}"
}

# ---------------------------------------------------------------------------
# --self-test: hermetic fixtures over a miniature tree with the real shapes.
#
# Both directions for every rule: the pinned tree passes, and each way a
# generated file can drift from its pin fails with the message that names it.
# The count is pinned by EQUALITY — a floor lets a deleted fixture hide.
# ---------------------------------------------------------------------------
self_test() {
  local -r SELF_TEST_FIXTURES=8
  local tmp fails=0 checked=0
  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp}'" RETURN

  local root="${tmp}/repo"
  local pins="${root}/scripts/ci/generated_bridge.sha256"
  local dart="${root}/haven/lib/src/rust/frb_generated.dart"
  local rs="${root}/haven/rust_builder/src/frb_generated.rs"

  _clean_tree() {
    rm -rf "${root}"
    mkdir -p "${root}/haven/lib/src/rust" "${root}/haven/rust_builder/src" \
      "${root}/scripts/ci"

    cat >"${root}/haven/rust_builder/Cargo.toml" <<'TOML'
[dependencies]
flutter_rust_bridge = "=2.11.1"
TOML

    cat >"${root}/haven/pubspec.yaml" <<'YAML'
dependencies:
  flutter_rust_bridge: 2.11.1
YAML

    cat >"${dart}" <<'DART'
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

BacklogOutcomeFfi dco_decode_backlog_outcome_ffi(dynamic raw) {
  return BacklogOutcomeFfi.values[raw as int];
}
DART

    cat >"${rs}" <<'RS'
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

impl SseEncode for crate::api::BacklogOutcomeFfi {
    fn sse_encode(self, serializer: &mut SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::BacklogOutcomeFfi::Settled => 0,
                crate::api::BacklogOutcomeFfi::TimedOut => 1,
            },
            serializer,
        );
    }
}
RS

    repin "${root}" "${pins}" >/dev/null
  }

  _run_all() { run_all_checks "${root}" "${pins}"; }

  _fixture() { # <label> <want-rc> <want-msg-substring> <mutation...>
    local label="$1" want_rc="$2" want_msg="$3"
    shift 3
    _clean_tree
    "$@"

    local out got=0
    out="$(_run_all 2>&1)" || got=$?
    checked=$(( checked + 1 ))

    if [[ "${got}" -ne "${want_rc}" ]]; then
      printf '  \033[1;31mFAIL\033[0m %s (want rc=%d, got rc=%d)\n' "${label}" "${want_rc}" "${got}" >&2
      printf '%s\n' "${out}" >&2
      fails=1
      return
    fi
    if [[ -n "${want_msg}" && "${out}" != *"${want_msg}"* ]]; then
      printf '  \033[1;31mFAIL\033[0m %s (rc=%d, but no message matched %q)\n' "${label}" "${got}" "${want_msg}" >&2
      printf '%s\n' "${out}" >&2
      fails=1
      return
    fi
    printf '  \033[1;32mPASS\033[0m %s (rc=%d)\n' "${label}" "${got}"
  }

  _noop() { :; }
  _sed() { sed -i "$1" "$2"; }
  _rm() { rm -f "$1"; }
  # A generated file the pin file has never heard of.
  _newfile() {
    mkdir -p "$(dirname "$1")"
    printf '%s\n%s\n' \
      '// This file is automatically generated, so please do not edit it.' \
      '// @generated by `flutter_rust_bridge`@ 2.11.1.' >"$1"
  }
  # A regeneration by a DIFFERENT codegen, pin file updated with it — so the
  # bytes agree with their pin and only the stamp gives it away.
  _restamp() {
    sed -i 's/`@ 2\.11\.1\./`@ 2.12.0./' "$1"
    repin "${root}" "${pins}" >/dev/null
  }
  # The marker this scanner discovers by, gone from every file.
  _degenerate() { sed -i '/@generated by/d' "${dart}" "${rs}"; }

  # 1. A freshly pinned tree passes.
  _fixture 'a freshly pinned tree passes' 0 '' _noop

  # 2. THE defect: `BacklogOutcomeFfi`'s encoding inverted by hand, decoder left
  #    alone. Well-typed on both sides, invisible to every test, and it makes
  #    each burst read a real backlog TIMEOUT as "settled" and publish at a
  #    stale epoch.
  _fixture 'an inverted SseEncode discriminant fails' 1 'does not match its pin' \
    _sed 's/Settled => 0,/Settled => 1,/' "${rs}"

  # 3. ...and the same on the Dart half.
  _fixture 'an edited generated Dart file fails' 1 'does not match its pin' \
    _sed 's/BacklogOutcomeFfi.values\[raw as int\]/BacklogOutcomeFfi.settled/' "${dart}"

  # 4. A NEW generated file, unpinned: a new pair of codecs nothing compares.
  _fixture 'a new unpinned generated file fails' 1 'carries no pin' \
    _newfile "${root}/haven/lib/src/rust/location/types.dart"

  # 5. A generated file deleted while its pin stays.
  _fixture 'a deleted generated file fails' 1 'is pinned but is no longer a generated file' \
    _rm "${dart}"

  # 6. A repin from a DIFFERENT codegen — the drift a byte pin alone cannot see,
  #    because the bytes and the pin move together.
  _fixture 'a file stamped by another codegen version fails' 1 'was generated by flutter_rust_bridge' \
    _restamp "${rs}"

  # 7. The two manifests disagreeing about the runtime the codecs link against.
  _fixture 'Cargo.toml and pubspec.yaml pinning different versions fails' 1 \
    'runtime versions disagree' \
    _sed 's/flutter_rust_bridge: 2.11.1/flutter_rust_bridge: 2.12.0/' "${root}/haven/pubspec.yaml"

  # 8. Anti-vacuity for the scanner itself: with no generated file to find, this
  #    guard must FAIL rather than pass over an empty set.
  _fixture 'a tree with no generated file at all fails' 1 'found no flutter_rust_bridge-generated file' \
    _degenerate

  if (( checked != SELF_TEST_FIXTURES )); then
    echo "SELF-TEST FAIL: ran ${checked} fixture(s), expected ${SELF_TEST_FIXTURES}" >&2
    fails=1
  fi
  if (( fails != 0 )); then
    echo "check_generated_bridge_pinned.sh --self-test: FAILED" >&2
    return 1
  fi
  echo "check_generated_bridge_pinned.sh --self-test: ${checked} fixtures passed"
  return 0
}

if [[ "${1:-}" == "--self-test" ]]; then
  self_test
  exit $?
fi

if [[ "${1:-}" == "--repin" ]]; then
  repin "${REPO_ROOT}" "${PIN_FILE}"
  exit 0
fi

for p in "${GENERATED_ROOTS[@]}"; do
  [[ -d "${REPO_ROOT}/${p}" ]] || { echo "ERROR: ${REPO_ROOT}/${p} not found" >&2; exit 2; }
done

log "Checking the generated bridge files against their pins ..."
if ! run_all_checks "${REPO_ROOT}" "${PIN_FILE}"; then
  echo "check_generated_bridge_pinned.sh: FAILED" >&2
  exit 1
fi
log "OK: every flutter_rust_bridge-generated file matches its pinned bytes and the codegen version both manifests pin."
