// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HavenCore>>
abstract class HavenCore implements RustOpaqueInterface {
  static Future<HavenCore> default_() =>
      RustLib.instance.api.crateApiHavenCoreDefault();

  /// Placeholder for future initialization logic.
  ///
  /// Currently a no-op that returns success.
  ///
  /// # Errors
  ///
  /// Returns `Err` if initialization fails (currently never fails).
  Future<void> initialize();

  /// Returns whether the core has been initialized.
  ///
  /// This is a synchronous FFI call since it's a simple getter.
  ///
  /// # Examples
  ///
  /// ```
  /// use haven_core::HavenCore;
  ///
  /// let core = HavenCore::new();
  /// assert!(core.is_initialized());
  /// ```
  bool isInitialized();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new `HavenCore` instance.
  ///
  /// # Examples
  ///
  /// ```
  /// use haven_core::HavenCore;
  ///
  /// let core = HavenCore::new();
  /// ```
  static Future<HavenCore> newInstance() =>
      RustLib.instance.api.crateApiHavenCoreNew();
}
