// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1561116992;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_haven',
        ioDirectory: 'rust_builder/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<HavenCore> crateApiHavenCoreDefault();

  LocationSettings crateApiHavenCoreGetLocationSettings({
    required HavenCore that,
  });

  Future<void> crateApiHavenCoreInitialize({required HavenCore that});

  bool crateApiHavenCoreIsInitialized({required HavenCore that});

  Future<HavenCore> crateApiHavenCoreNew();

  void crateApiHavenCoreSetLocationSettings({
    required HavenCore that,
    required LocationSettings settings,
  });

  LocationMessage crateApiHavenCoreUpdateLocation({
    required HavenCore that,
    required double latitude,
    required double longitude,
  });

  UnsignedLocationEventFfi crateApiLocationEventServiceCreateUnsignedEvent({
    required LocationEventService that,
    required LocationMessage location,
  });

  Future<LocationEventService> crateApiLocationEventServiceDefault();

  Future<LocationEventService> crateApiLocationEventServiceNew();

  bool crateApiLocationEventServiceVerifySignature({
    required LocationEventService that,
    required SignedLocationEventFfi event,
  });

  PlatformInt64 crateApiLocationMessageExpiresAt({
    required LocationMessage that,
  });

  String crateApiLocationMessageGeohash({required LocationMessage that});

  bool crateApiLocationMessageIsExpired({required LocationMessage that});

  double crateApiLocationMessageLatitude({required LocationMessage that});

  double crateApiLocationMessageLongitude({required LocationMessage that});

  LocationPrecision crateApiLocationMessagePrecision({
    required LocationMessage that,
  });

  PlatformInt64 crateApiLocationMessageTimestamp({
    required LocationMessage that,
  });

  bool crateApiLocationSettingsIncludeGeohashInEvents({
    required LocationSettings that,
  });

  Future<LocationSettings> crateApiLocationSettingsNew({
    required LocationPrecision precision,
    required int updateIntervalMinutes,
    required bool includeGeohashInEvents,
  });

  LocationPrecision crateApiLocationSettingsPrecision({
    required LocationSettings that,
  });

  int crateApiLocationSettingsUpdateIntervalMinutes({
    required LocationSettings that,
  });

  Future<void> crateApiNostrIdentityManagerClearCache({
    required NostrIdentityManager that,
  });

  Future<PublicIdentity> crateApiNostrIdentityManagerCreateIdentity({
    required NostrIdentityManager that,
  });

  Future<NostrIdentityManager> crateApiNostrIdentityManagerDefault();

  Future<void> crateApiNostrIdentityManagerDeleteIdentity({
    required NostrIdentityManager that,
  });

  Future<String> crateApiNostrIdentityManagerExportNsec({
    required NostrIdentityManager that,
  });

  PublicIdentity? crateApiNostrIdentityManagerGetIdentity({
    required NostrIdentityManager that,
  });

  Future<Uint8List> crateApiNostrIdentityManagerGetSecretBytes({
    required NostrIdentityManager that,
  });

  bool crateApiNostrIdentityManagerHasIdentity({
    required NostrIdentityManager that,
  });

  Future<PublicIdentity> crateApiNostrIdentityManagerImportFromNsec({
    required NostrIdentityManager that,
    required String nsec,
  });

  Future<PublicIdentity> crateApiNostrIdentityManagerLoadFromBytes({
    required NostrIdentityManager that,
    required List<int> secretBytes,
  });

  Future<NostrIdentityManager> crateApiNostrIdentityManagerNew();

  String crateApiNostrIdentityManagerPubkeyHex({
    required NostrIdentityManager that,
  });

  Future<String> crateApiNostrIdentityManagerSign({
    required NostrIdentityManager that,
    required List<int> messageHash,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HavenCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HavenCore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_HavenCorePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationEventService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationEventService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationEventServicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationMessage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationMessage;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationMessagePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationPrecision;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationPrecision;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationPrecisionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationSettings;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationSettings;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationSettingsPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostrIdentityManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostrIdentityManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NostrIdentityManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<HavenCore> crateApiHavenCoreDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreDefaultConstMeta =>
      const TaskConstMeta(debugName: "HavenCore_default", argNames: []);

  @override
  LocationSettings crateApiHavenCoreGetLocationSettings({
    required HavenCore that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreGetLocationSettingsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreGetLocationSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "HavenCore_get_location_settings",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiHavenCoreInitialize({required HavenCore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHavenCoreInitializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreInitializeConstMeta =>
      const TaskConstMeta(
        debugName: "HavenCore_initialize",
        argNames: ["that"],
      );

  @override
  bool crateApiHavenCoreIsInitialized({required HavenCore that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreIsInitializedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreIsInitializedConstMeta =>
      const TaskConstMeta(
        debugName: "HavenCore_is_initialized",
        argNames: ["that"],
      );

  @override
  Future<HavenCore> crateApiHavenCoreNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreNewConstMeta =>
      const TaskConstMeta(debugName: "HavenCore_new", argNames: []);

  @override
  void crateApiHavenCoreSetLocationSettings({
    required HavenCore that,
    required LocationSettings settings,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
            settings,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreSetLocationSettingsConstMeta,
        argValues: [that, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreSetLocationSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "HavenCore_set_location_settings",
        argNames: ["that", "settings"],
      );

  @override
  LocationMessage crateApiHavenCoreUpdateLocation({
    required HavenCore that,
    required double latitude,
    required double longitude,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
            that,
            serializer,
          );
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHavenCoreUpdateLocationConstMeta,
        argValues: [that, latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHavenCoreUpdateLocationConstMeta =>
      const TaskConstMeta(
        debugName: "HavenCore_update_location",
        argNames: ["that", "latitude", "longitude"],
      );

  @override
  UnsignedLocationEventFfi crateApiLocationEventServiceCreateUnsignedEvent({
    required LocationEventService that,
    required LocationMessage location,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
            that,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            location,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unsigned_location_event_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLocationEventServiceCreateUnsignedEventConstMeta,
        argValues: [that, location],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationEventServiceCreateUnsignedEventConstMeta =>
      const TaskConstMeta(
        debugName: "LocationEventService_create_unsigned_event",
        argNames: ["that", "location"],
      );

  @override
  Future<LocationEventService> crateApiLocationEventServiceDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationEventServiceDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationEventServiceDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "LocationEventService_default",
        argNames: [],
      );

  @override
  Future<LocationEventService> crateApiLocationEventServiceNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationEventServiceNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationEventServiceNewConstMeta =>
      const TaskConstMeta(debugName: "LocationEventService_new", argNames: []);

  @override
  bool crateApiLocationEventServiceVerifySignature({
    required LocationEventService that,
    required SignedLocationEventFfi event,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_signed_location_event_ffi(event, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLocationEventServiceVerifySignatureConstMeta,
        argValues: [that, event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationEventServiceVerifySignatureConstMeta =>
      const TaskConstMeta(
        debugName: "LocationEventService_verify_signature",
        argNames: ["that", "event"],
      );

  @override
  PlatformInt64 crateApiLocationMessageExpiresAt({
    required LocationMessage that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageExpiresAtConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageExpiresAtConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_expires_at",
        argNames: ["that"],
      );

  @override
  String crateApiLocationMessageGeohash({required LocationMessage that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageGeohashConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageGeohashConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_geohash",
        argNames: ["that"],
      );

  @override
  bool crateApiLocationMessageIsExpired({required LocationMessage that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageIsExpiredConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageIsExpiredConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_is_expired",
        argNames: ["that"],
      );

  @override
  double crateApiLocationMessageLatitude({required LocationMessage that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageLatitudeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageLatitudeConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_latitude",
        argNames: ["that"],
      );

  @override
  double crateApiLocationMessageLongitude({required LocationMessage that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageLongitudeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageLongitudeConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_longitude",
        argNames: ["that"],
      );

  @override
  LocationPrecision crateApiLocationMessagePrecision({
    required LocationMessage that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessagePrecisionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessagePrecisionConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_precision",
        argNames: ["that"],
      );

  @override
  PlatformInt64 crateApiLocationMessageTimestamp({
    required LocationMessage that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationMessageTimestampConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationMessageTimestampConstMeta =>
      const TaskConstMeta(
        debugName: "LocationMessage_timestamp",
        argNames: ["that"],
      );

  @override
  bool crateApiLocationSettingsIncludeGeohashInEvents({
    required LocationSettings that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationSettingsIncludeGeohashInEventsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationSettingsIncludeGeohashInEventsConstMeta =>
      const TaskConstMeta(
        debugName: "LocationSettings_include_geohash_in_events",
        argNames: ["that"],
      );

  @override
  Future<LocationSettings> crateApiLocationSettingsNew({
    required LocationPrecision precision,
    required int updateIntervalMinutes,
    required bool includeGeohashInEvents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
            precision,
            serializer,
          );
          sse_encode_u_32(updateIntervalMinutes, serializer);
          sse_encode_bool(includeGeohashInEvents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationSettingsNewConstMeta,
        argValues: [precision, updateIntervalMinutes, includeGeohashInEvents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationSettingsNewConstMeta =>
      const TaskConstMeta(
        debugName: "LocationSettings_new",
        argNames: [
          "precision",
          "updateIntervalMinutes",
          "includeGeohashInEvents",
        ],
      );

  @override
  LocationPrecision crateApiLocationSettingsPrecision({
    required LocationSettings that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationSettingsPrecisionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationSettingsPrecisionConstMeta =>
      const TaskConstMeta(
        debugName: "LocationSettings_precision",
        argNames: ["that"],
      );

  @override
  int crateApiLocationSettingsUpdateIntervalMinutes({
    required LocationSettings that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocationSettingsUpdateIntervalMinutesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocationSettingsUpdateIntervalMinutesConstMeta =>
      const TaskConstMeta(
        debugName: "LocationSettings_update_interval_minutes",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiNostrIdentityManagerClearCache({
    required NostrIdentityManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrIdentityManagerClearCacheConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerClearCacheConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_clear_cache",
        argNames: ["that"],
      );

  @override
  Future<PublicIdentity> crateApiNostrIdentityManagerCreateIdentity({
    required NostrIdentityManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_public_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerCreateIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerCreateIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_create_identity",
        argNames: ["that"],
      );

  @override
  Future<NostrIdentityManager> crateApiNostrIdentityManagerDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrIdentityManagerDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_default",
        argNames: [],
      );

  @override
  Future<void> crateApiNostrIdentityManagerDeleteIdentity({
    required NostrIdentityManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerDeleteIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerDeleteIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_delete_identity",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiNostrIdentityManagerExportNsec({
    required NostrIdentityManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerExportNsecConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerExportNsecConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_export_nsec",
        argNames: ["that"],
      );

  @override
  PublicIdentity? crateApiNostrIdentityManagerGetIdentity({
    required NostrIdentityManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_public_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerGetIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerGetIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_get_identity",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiNostrIdentityManagerGetSecretBytes({
    required NostrIdentityManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerGetSecretBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerGetSecretBytesConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_get_secret_bytes",
        argNames: ["that"],
      );

  @override
  bool crateApiNostrIdentityManagerHasIdentity({
    required NostrIdentityManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrIdentityManagerHasIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerHasIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_has_identity",
        argNames: ["that"],
      );

  @override
  Future<PublicIdentity> crateApiNostrIdentityManagerImportFromNsec({
    required NostrIdentityManager that,
    required String nsec,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          sse_encode_String(nsec, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_public_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerImportFromNsecConstMeta,
        argValues: [that, nsec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerImportFromNsecConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_import_from_nsec",
        argNames: ["that", "nsec"],
      );

  @override
  Future<PublicIdentity> crateApiNostrIdentityManagerLoadFromBytes({
    required NostrIdentityManager that,
    required List<int> secretBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(secretBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_public_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerLoadFromBytesConstMeta,
        argValues: [that, secretBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerLoadFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_load_from_bytes",
        argNames: ["that", "secretBytes"],
      );

  @override
  Future<NostrIdentityManager> crateApiNostrIdentityManagerNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrIdentityManagerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerNewConstMeta =>
      const TaskConstMeta(debugName: "NostrIdentityManager_new", argNames: []);

  @override
  String crateApiNostrIdentityManagerPubkeyHex({
    required NostrIdentityManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerPubkeyHexConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerPubkeyHexConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_pubkey_hex",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiNostrIdentityManagerSign({
    required NostrIdentityManager that,
    required List<int> messageHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(messageHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrIdentityManagerSignConstMeta,
        argValues: [that, messageHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrIdentityManagerSignConstMeta =>
      const TaskConstMeta(
        debugName: "NostrIdentityManager_sign",
        argNames: ["that", "messageHash"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HavenCore => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HavenCore => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationEventService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationEventService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationMessage => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationMessage => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationPrecision => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationPrecision => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocationSettings => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocationSettings => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostrIdentityManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostrIdentityManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager;

  @protected
  HavenCore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HavenCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationEventService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationMessage
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationMessageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationPrecision
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationPrecisionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationSettings
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostrIdentityManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HavenCore
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HavenCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HavenCore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HavenCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationEventService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationMessage
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationMessageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationSettings
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostrIdentityManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HavenCore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HavenCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationEventService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationMessage
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationMessageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationPrecision
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationPrecisionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocationSettings
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostrIdentityManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PublicIdentity dco_decode_box_autoadd_public_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_public_identity(raw);
  }

  @protected
  SignedLocationEventFfi dco_decode_box_autoadd_signed_location_event_ffi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_signed_location_event_ffi(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PublicIdentity? dco_decode_opt_box_autoadd_public_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_public_identity(raw);
  }

  @protected
  PublicIdentity dco_decode_public_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PublicIdentity(
      pubkeyHex: dco_decode_String(arr[0]),
      npub: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  SignedLocationEventFfi dco_decode_signed_location_event_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SignedLocationEventFfi(
      id: dco_decode_String(arr[0]),
      pubkey: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      kind: dco_decode_u_16(arr[3]),
      tags: dco_decode_list_list_String(arr[4]),
      content: dco_decode_String(arr[5]),
      sig: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UnsignedLocationEventFfi dco_decode_unsigned_location_event_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UnsignedLocationEventFfi(
      kind: dco_decode_u_16(arr[0]),
      content: dco_decode_String(arr[1]),
      tags: dco_decode_list_list_String(arr[2]),
      createdAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  HavenCore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HavenCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationEventService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationMessage
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationMessageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationPrecision
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationPrecisionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationSettings
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostrIdentityManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HavenCore
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HavenCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HavenCore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HavenCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationEventService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationMessage
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationMessageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationSettings
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostrIdentityManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HavenCore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HavenCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationEventService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationEventServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationMessage
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationMessageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationPrecision
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationPrecisionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocationSettings
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocationSettingsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostrIdentityManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostrIdentityManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PublicIdentity sse_decode_box_autoadd_public_identity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_public_identity(deserializer));
  }

  @protected
  SignedLocationEventFfi sse_decode_box_autoadd_signed_location_event_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_signed_location_event_ffi(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PublicIdentity? sse_decode_opt_box_autoadd_public_identity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_public_identity(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublicIdentity sse_decode_public_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pubkeyHex = sse_decode_String(deserializer);
    var var_npub = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return PublicIdentity(
      pubkeyHex: var_pubkeyHex,
      npub: var_npub,
      createdAt: var_createdAt,
    );
  }

  @protected
  SignedLocationEventFfi sse_decode_signed_location_event_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_pubkey = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_u_16(deserializer);
    var var_tags = sse_decode_list_list_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_sig = sse_decode_String(deserializer);
    return SignedLocationEventFfi(
      id: var_id,
      pubkey: var_pubkey,
      createdAt: var_createdAt,
      kind: var_kind,
      tags: var_tags,
      content: var_content,
      sig: var_sig,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UnsignedLocationEventFfi sse_decode_unsigned_location_event_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_u_16(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_list_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return UnsignedLocationEventFfi(
      kind: var_kind,
      content: var_content,
      tags: var_tags,
      createdAt: var_createdAt,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HavenCoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationEventServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationMessageImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    LocationPrecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationPrecisionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationSettingsImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostrIdentityManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HavenCoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HavenCoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationEventServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationMessageImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationSettingsImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostrIdentityManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HavenCoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationEventServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationMessageImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    LocationPrecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationPrecisionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocationSettingsImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostrIdentityManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_public_identity(
    PublicIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_public_identity(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_signed_location_event_ffi(
    SignedLocationEventFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_signed_location_event_ffi(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_public_identity(
    PublicIdentity? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_public_identity(self, serializer);
    }
  }

  @protected
  void sse_encode_public_identity(
    PublicIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pubkeyHex, serializer);
    sse_encode_String(self.npub, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_signed_location_event_ffi(
    SignedLocationEventFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.pubkey, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_u_16(self.kind, serializer);
    sse_encode_list_list_String(self.tags, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.sig, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_unsigned_location_event_ffi(
    UnsignedLocationEventFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_list_list_String(self.tags, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class HavenCoreImpl extends RustOpaque implements HavenCore {
  // Not to be used by end users
  HavenCoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HavenCoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HavenCore,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HavenCore,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HavenCorePtr,
  );

  /// Gets the current location settings.
  LocationSettings getLocationSettings() =>
      RustLib.instance.api.crateApiHavenCoreGetLocationSettings(that: this);

  /// Initializes the core.
  Future<void> initialize() =>
      RustLib.instance.api.crateApiHavenCoreInitialize(that: this);

  /// Returns whether the core has been initialized.
  bool isInitialized() =>
      RustLib.instance.api.crateApiHavenCoreIsInitialized(that: this);

  /// Updates the location settings.
  void setLocationSettings({required LocationSettings settings}) => RustLib
      .instance
      .api
      .crateApiHavenCoreSetLocationSettings(that: this, settings: settings);

  /// Processes raw location data and returns an obfuscated `LocationMessage`.
  LocationMessage updateLocation({
    required double latitude,
    required double longitude,
  }) => RustLib.instance.api.crateApiHavenCoreUpdateLocation(
    that: this,
    latitude: latitude,
    longitude: longitude,
  );
}

@sealed
class LocationEventServiceImpl extends RustOpaque
    implements LocationEventService {
  // Not to be used by end users
  LocationEventServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocationEventServiceImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_LocationEventService,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LocationEventService,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LocationEventServicePtr,
  );

  /// Creates an unsigned location event (kind 30078).
  ///
  /// This is the inner event that gets encrypted before being wrapped
  /// in a kind 445 group message.
  UnsignedLocationEventFfi createUnsignedEvent({
    required LocationMessage location,
  }) => RustLib.instance.api.crateApiLocationEventServiceCreateUnsignedEvent(
    that: this,
    location: location,
  );

  /// Verifies the signature of a signed event.
  ///
  /// Returns `true` if the signature is valid, `false` otherwise.
  bool verifySignature({required SignedLocationEventFfi event}) => RustLib
      .instance
      .api
      .crateApiLocationEventServiceVerifySignature(that: this, event: event);
}

@sealed
class LocationMessageImpl extends RustOpaque implements LocationMessage {
  // Not to be used by end users
  LocationMessageImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocationMessageImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LocationMessage,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocationMessage,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocationMessagePtr,
  );

  /// Gets the expiration time as Unix timestamp (seconds since epoch).
  PlatformInt64 expiresAt() =>
      RustLib.instance.api.crateApiLocationMessageExpiresAt(that: this);

  /// Gets the geohash representation.
  String geohash() =>
      RustLib.instance.api.crateApiLocationMessageGeohash(that: this);

  /// Checks if the location has expired.
  bool isExpired() =>
      RustLib.instance.api.crateApiLocationMessageIsExpired(that: this);

  /// Gets the obfuscated latitude.
  double latitude() =>
      RustLib.instance.api.crateApiLocationMessageLatitude(that: this);

  /// Gets the obfuscated longitude.
  double longitude() =>
      RustLib.instance.api.crateApiLocationMessageLongitude(that: this);

  /// Gets the precision level.
  LocationPrecision precision() =>
      RustLib.instance.api.crateApiLocationMessagePrecision(that: this);

  /// Gets the timestamp as Unix timestamp (seconds since epoch).
  PlatformInt64 timestamp() =>
      RustLib.instance.api.crateApiLocationMessageTimestamp(that: this);
}

@sealed
class LocationPrecisionImpl extends RustOpaque implements LocationPrecision {
  // Not to be used by end users
  LocationPrecisionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocationPrecisionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LocationPrecision,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocationPrecision,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LocationPrecisionPtr,
  );
}

@sealed
class LocationSettingsImpl extends RustOpaque implements LocationSettings {
  // Not to be used by end users
  LocationSettingsImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocationSettingsImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LocationSettings,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocationSettings,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LocationSettingsPtr,
  );

  /// Gets whether to include geohash in events.
  bool includeGeohashInEvents() => RustLib.instance.api
      .crateApiLocationSettingsIncludeGeohashInEvents(that: this);

  /// Gets the precision level.
  LocationPrecision precision() =>
      RustLib.instance.api.crateApiLocationSettingsPrecision(that: this);

  /// Gets the update interval in minutes.
  int updateIntervalMinutes() => RustLib.instance.api
      .crateApiLocationSettingsUpdateIntervalMinutes(that: this);
}

@sealed
class NostrIdentityManagerImpl extends RustOpaque
    implements NostrIdentityManager {
  // Not to be used by end users
  NostrIdentityManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NostrIdentityManagerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_NostrIdentityManager,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_NostrIdentityManager,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_NostrIdentityManagerPtr,
  );

  /// Clears the in-memory cache.
  ///
  /// Call this when the app goes to background.
  Future<void> clearCache() =>
      RustLib.instance.api.crateApiNostrIdentityManagerClearCache(that: this);

  /// Creates a new random identity.
  ///
  /// After calling this, use `get_secret_bytes()` to persist the secret.
  Future<PublicIdentity> createIdentity() => RustLib.instance.api
      .crateApiNostrIdentityManagerCreateIdentity(that: this);

  /// Deletes the identity.
  Future<void> deleteIdentity() => RustLib.instance.api
      .crateApiNostrIdentityManagerDeleteIdentity(that: this);

  /// Exports the identity as nsec for backup.
  ///
  /// # Security Warning
  ///
  /// This exposes the secret key. Only use for user-initiated backup.
  Future<String> exportNsec() =>
      RustLib.instance.api.crateApiNostrIdentityManagerExportNsec(that: this);

  /// Gets the current public identity.
  PublicIdentity? getIdentity() =>
      RustLib.instance.api.crateApiNostrIdentityManagerGetIdentity(that: this);

  /// Gets the secret bytes for persistence in Flutter secure storage.
  ///
  /// # Security Warning
  ///
  /// Handle these bytes with extreme care. They should only be stored
  /// in platform secure storage (iOS Keychain, Android Keystore, etc.).
  /// The bytes are automatically zeroized in Rust memory after this call.
  Future<Uint8List> getSecretBytes() => RustLib.instance.api
      .crateApiNostrIdentityManagerGetSecretBytes(that: this);

  /// Checks if an identity is loaded.
  bool hasIdentity() =>
      RustLib.instance.api.crateApiNostrIdentityManagerHasIdentity(that: this);

  /// Imports an identity from an nsec string.
  ///
  /// After calling this, use `get_secret_bytes()` to persist the secret.
  Future<PublicIdentity> importFromNsec({required String nsec}) => RustLib
      .instance
      .api
      .crateApiNostrIdentityManagerImportFromNsec(that: this, nsec: nsec);

  /// Loads an identity from raw secret bytes (retrieved from Flutter secure storage).
  ///
  /// Call this on app startup if you have persisted secret bytes.
  Future<PublicIdentity> loadFromBytes({required List<int> secretBytes}) =>
      RustLib.instance.api.crateApiNostrIdentityManagerLoadFromBytes(
        that: this,
        secretBytes: secretBytes,
      );

  /// Gets the public key as hex string (for MDK operations).
  String pubkeyHex() =>
      RustLib.instance.api.crateApiNostrIdentityManagerPubkeyHex(that: this);

  /// Signs a 32-byte message hash.
  ///
  /// Returns the signature as a 128-character hex string.
  Future<String> sign({required List<int> messageHash}) => RustLib.instance.api
      .crateApiNostrIdentityManagerSign(that: this, messageHash: messageHash);
}
