// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CircleManagerFfiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HavenCorePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationEventServicePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationMessagePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationPrecisionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocationSettingsPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NostrIdentityManagerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager;

  @protected
  CircleManagerFfi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    dynamic raw,
  );

  @protected
  HavenCore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  );

  @protected
  LocationEventService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  );

  @protected
  LocationMessage
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  );

  @protected
  LocationPrecision
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    dynamic raw,
  );

  @protected
  LocationSettings
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  );

  @protected
  NostrIdentityManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  );

  @protected
  HavenCore
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  );

  @protected
  CircleManagerFfi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    dynamic raw,
  );

  @protected
  HavenCore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  );

  @protected
  LocationEventService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  );

  @protected
  LocationMessage
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  );

  @protected
  LocationSettings
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  );

  @protected
  NostrIdentityManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  );

  @protected
  CircleManagerFfi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    dynamic raw,
  );

  @protected
  HavenCore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    dynamic raw,
  );

  @protected
  LocationEventService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    dynamic raw,
  );

  @protected
  LocationMessage
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    dynamic raw,
  );

  @protected
  LocationPrecision
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    dynamic raw,
  );

  @protected
  LocationSettings
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    dynamic raw,
  );

  @protected
  NostrIdentityManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CircleWithMembersFfi dco_decode_box_autoadd_circle_with_members_ffi(
    dynamic raw,
  );

  @protected
  ContactFfi dco_decode_box_autoadd_contact_ffi(dynamic raw);

  @protected
  PublicIdentity dco_decode_box_autoadd_public_identity(dynamic raw);

  @protected
  SignedLocationEventFfi dco_decode_box_autoadd_signed_location_event_ffi(
    dynamic raw,
  );

  @protected
  CircleCreationResultFfi dco_decode_circle_creation_result_ffi(dynamic raw);

  @protected
  CircleFfi dco_decode_circle_ffi(dynamic raw);

  @protected
  CircleMemberFfi dco_decode_circle_member_ffi(dynamic raw);

  @protected
  CircleWithMembersFfi dco_decode_circle_with_members_ffi(dynamic raw);

  @protected
  ContactFfi dco_decode_contact_ffi(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InvitationFfi dco_decode_invitation_ffi(dynamic raw);

  @protected
  KeyPackageBundleFfi dco_decode_key_package_bundle_ffi(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CircleMemberFfi> dco_decode_list_circle_member_ffi(dynamic raw);

  @protected
  List<CircleWithMembersFfi> dco_decode_list_circle_with_members_ffi(
    dynamic raw,
  );

  @protected
  List<ContactFfi> dco_decode_list_contact_ffi(dynamic raw);

  @protected
  List<InvitationFfi> dco_decode_list_invitation_ffi(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<UnsignedEventFfi> dco_decode_list_unsigned_event_ffi(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CircleWithMembersFfi? dco_decode_opt_box_autoadd_circle_with_members_ffi(
    dynamic raw,
  );

  @protected
  ContactFfi? dco_decode_opt_box_autoadd_contact_ffi(dynamic raw);

  @protected
  PublicIdentity? dco_decode_opt_box_autoadd_public_identity(dynamic raw);

  @protected
  PublicIdentity dco_decode_public_identity(dynamic raw);

  @protected
  SignedEventFfi dco_decode_signed_event_ffi(dynamic raw);

  @protected
  SignedLocationEventFfi dco_decode_signed_location_event_ffi(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnsignedEventFfi dco_decode_unsigned_event_ffi(dynamic raw);

  @protected
  UnsignedLocationEventFfi dco_decode_unsigned_location_event_ffi(dynamic raw);

  @protected
  UpdateGroupResultFfi dco_decode_update_group_result_ffi(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  CircleManagerFfi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    SseDeserializer deserializer,
  );

  @protected
  HavenCore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  );

  @protected
  LocationEventService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  );

  @protected
  LocationMessage
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  );

  @protected
  LocationPrecision
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    SseDeserializer deserializer,
  );

  @protected
  LocationSettings
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  );

  @protected
  NostrIdentityManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  );

  @protected
  HavenCore
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  );

  @protected
  CircleManagerFfi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    SseDeserializer deserializer,
  );

  @protected
  HavenCore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  );

  @protected
  LocationEventService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  );

  @protected
  LocationMessage
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  );

  @protected
  LocationSettings
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  );

  @protected
  NostrIdentityManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  );

  @protected
  CircleManagerFfi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    SseDeserializer deserializer,
  );

  @protected
  HavenCore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    SseDeserializer deserializer,
  );

  @protected
  LocationEventService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    SseDeserializer deserializer,
  );

  @protected
  LocationMessage
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    SseDeserializer deserializer,
  );

  @protected
  LocationPrecision
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    SseDeserializer deserializer,
  );

  @protected
  LocationSettings
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    SseDeserializer deserializer,
  );

  @protected
  NostrIdentityManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CircleWithMembersFfi sse_decode_box_autoadd_circle_with_members_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ContactFfi sse_decode_box_autoadd_contact_ffi(SseDeserializer deserializer);

  @protected
  PublicIdentity sse_decode_box_autoadd_public_identity(
    SseDeserializer deserializer,
  );

  @protected
  SignedLocationEventFfi sse_decode_box_autoadd_signed_location_event_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CircleCreationResultFfi sse_decode_circle_creation_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CircleFfi sse_decode_circle_ffi(SseDeserializer deserializer);

  @protected
  CircleMemberFfi sse_decode_circle_member_ffi(SseDeserializer deserializer);

  @protected
  CircleWithMembersFfi sse_decode_circle_with_members_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ContactFfi sse_decode_contact_ffi(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InvitationFfi sse_decode_invitation_ffi(SseDeserializer deserializer);

  @protected
  KeyPackageBundleFfi sse_decode_key_package_bundle_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CircleMemberFfi> sse_decode_list_circle_member_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<CircleWithMembersFfi> sse_decode_list_circle_with_members_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ContactFfi> sse_decode_list_contact_ffi(SseDeserializer deserializer);

  @protected
  List<InvitationFfi> sse_decode_list_invitation_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<UnsignedEventFfi> sse_decode_list_unsigned_event_ffi(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CircleWithMembersFfi? sse_decode_opt_box_autoadd_circle_with_members_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ContactFfi? sse_decode_opt_box_autoadd_contact_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PublicIdentity? sse_decode_opt_box_autoadd_public_identity(
    SseDeserializer deserializer,
  );

  @protected
  PublicIdentity sse_decode_public_identity(SseDeserializer deserializer);

  @protected
  SignedEventFfi sse_decode_signed_event_ffi(SseDeserializer deserializer);

  @protected
  SignedLocationEventFfi sse_decode_signed_location_event_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnsignedEventFfi sse_decode_unsigned_event_ffi(SseDeserializer deserializer);

  @protected
  UnsignedLocationEventFfi sse_decode_unsigned_location_event_ffi(
    SseDeserializer deserializer,
  );

  @protected
  UpdateGroupResultFfi sse_decode_update_group_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    CircleManagerFfi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    LocationPrecision self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    CircleManagerFfi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    CircleManagerFfi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    HavenCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    LocationEventService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    LocationMessage self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    LocationPrecision self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    LocationSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    NostrIdentityManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_circle_with_members_ffi(
    CircleWithMembersFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_contact_ffi(
    ContactFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_public_identity(
    PublicIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_signed_location_event_ffi(
    SignedLocationEventFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_circle_creation_result_ffi(
    CircleCreationResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_circle_ffi(CircleFfi self, SseSerializer serializer);

  @protected
  void sse_encode_circle_member_ffi(
    CircleMemberFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_circle_with_members_ffi(
    CircleWithMembersFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_ffi(ContactFfi self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_invitation_ffi(InvitationFfi self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_bundle_ffi(
    KeyPackageBundleFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_circle_member_ffi(
    List<CircleMemberFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_circle_with_members_ffi(
    List<CircleWithMembersFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_contact_ffi(
    List<ContactFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_invitation_ffi(
    List<InvitationFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unsigned_event_ffi(
    List<UnsignedEventFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_circle_with_members_ffi(
    CircleWithMembersFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_contact_ffi(
    ContactFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_public_identity(
    PublicIdentity? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_public_identity(
    PublicIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_signed_event_ffi(
    SignedEventFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_signed_location_event_ffi(
    SignedLocationEventFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unsigned_event_ffi(
    UnsignedEventFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unsigned_location_event_ffi(
    UnsignedLocationEventFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_update_group_result_ffi(
    UpdateGroupResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCircleManagerFfi(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHavenCore(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationEventService(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationMessage(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationPrecision(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocationSettings(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostrIdentityManager(
    int ptr,
  );
}
