// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A privacy-focused location message.
///
/// This struct represents a location that has been obfuscated for privacy.
/// It only contains the minimum necessary information for family location sharing.
///
/// # Privacy Features
///
/// - Coordinates are obfuscated to the specified precision
/// - Metadata (device ID, altitude, speed, heading) is never serialized
/// - Automatic expiration (24 hours default)
/// - Geohash encoding for approximate location matching
///
/// # Example
///
/// ```
/// use haven_core::location::LocationMessage;
///
/// let location = LocationMessage::new(37.7749295, -122.4194155);
/// // Raw coordinates: 37.7749295, -122.4194155
/// // Obfuscated:      37.7749,    -122.4194 (4 decimals)
/// assert_eq!(location.latitude, 37.7749);
/// assert_eq!(location.longitude, -122.4194);
/// ```
class LocationMessage {
  /// Obfuscated latitude (precision determined by `precision` field)
  final double latitude;

  /// Obfuscated longitude (precision determined by `precision` field)
  final double longitude;

  /// Geohash representation for approximate location matching
  final String geohash;

  /// When location was recorded (UTC)
  final DateTime timestamp;

  /// When this location expires (24 hours default)
  final DateTime expiresAt;

  /// Precision level used for obfuscation
  final LocationPrecision precision;

  /// Device ID (not serialized for privacy)
  final String? deviceId;

  /// Raw GPS accuracy in meters (not serialized for privacy)
  final double? rawAccuracy;

  /// Altitude in meters (not serialized for privacy)
  final double? altitude;

  /// Speed in meters/second (not serialized for privacy)
  final double? speed;

  /// Heading in degrees (not serialized for privacy)
  final double? heading;

  const LocationMessage({
    required this.latitude,
    required this.longitude,
    required this.geohash,
    required this.timestamp,
    required this.expiresAt,
    required this.precision,
    this.deviceId,
    this.rawAccuracy,
    this.altitude,
    this.speed,
    this.heading,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      geohash.hashCode ^
      timestamp.hashCode ^
      expiresAt.hashCode ^
      precision.hashCode ^
      deviceId.hashCode ^
      rawAccuracy.hashCode ^
      altitude.hashCode ^
      speed.hashCode ^
      heading.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocationMessage &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          geohash == other.geohash &&
          timestamp == other.timestamp &&
          expiresAt == other.expiresAt &&
          precision == other.precision &&
          deviceId == other.deviceId &&
          rawAccuracy == other.rawAccuracy &&
          altitude == other.altitude &&
          speed == other.speed &&
          heading == other.heading;
}

/// Precision level for coordinate obfuscation.
///
/// Determines how many decimal places are retained when obfuscating coordinates.
/// Lower precision means more privacy but less accuracy.
///
/// The default precision is [LocationPrecision.enhanced] (5 decimal places),
/// which provides ~1.1m accuracy - sufficient for family location sharing.
///
/// # Precision Table
///
/// | Precision | Decimal Places | Approximate Radius |
/// |-----------|----------------|-------------------|
/// | Private   | 2              | ~1.1 km           |
/// | Standard  | 4              | ~11 m             |
/// | Enhanced  | 5              | ~1.1 m (default)  |
enum LocationPrecision {
  /// 2 decimal places (~1.1km radius) - maximum privacy
  private,

  /// 4 decimal places (~11m radius) - balanced privacy and accuracy
  standard,

  /// 5 decimal places (~1.1m radius) - default, precise family sharing
  enhanced,
}

/// Settings for location sharing.
///
/// These settings control how location data is collected, obfuscated, and shared.
class LocationSettings {
  /// Precision level for coordinate obfuscation
  final LocationPrecision precision;

  /// Update interval in minutes (5-60)
  final int updateIntervalMinutes;

  /// Whether to include geohash tags in Nostr events (default: false for privacy)
  ///
  /// When enabled:
  /// - Relays can filter events by approximate location (city-level)
  /// - Reduces data usage when traveling
  /// - Relays see which ~5km area you're in
  ///
  /// When disabled (default):
  /// - Maximum privacy - relays see nothing
  /// - Slightly higher data usage
  final bool includeGeohashInEvents;

  const LocationSettings({
    required this.precision,
    required this.updateIntervalMinutes,
    required this.includeGeohashInEvents,
  });

  @override
  int get hashCode =>
      precision.hashCode ^
      updateIntervalMinutes.hashCode ^
      includeGeohashInEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocationSettings &&
          runtimeType == other.runtimeType &&
          precision == other.precision &&
          updateIntervalMinutes == other.updateIntervalMinutes &&
          includeGeohashInEvents == other.includeGeohashInEvents;
}
